FROM centos:latest

RUN yum -y install epel-release; \
    yum -y install python-pip; yum clean all;

COPY . /app

WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
