---
- hosts: all
  become: yes
  tasks:
    - name: Install IUM repository
      yum: name=https://centos7.iuscommunity.org/ius-release.rpm state=installed

    - name: Install Python 3.6
      yum: name=python36u state=present update_cache=yes

    - name: Install pip
      yum: name=python36u-pip state=present update_cache=yes

    - name: install flask with pip
      pip:
        name: flask
        executable: pip3.6